import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button,  AppBar, Toolbar, Typography} from '@mui/material';


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="static" sx={{backgroundColor: '#E88800'}}>
        <Toolbar>
          <Typography>Magic-world</Typography>
        </Toolbar>
      </AppBar>

      <main className={styles.main}>
        <Button variant="contained">Hello World</Button>;
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
