export default [
  {
    id: 1,
    itemName: "Moldes desmontables",
    slug: "moldes-desmontables",
    price: 300,
    category: "Repostería",
    slugCategory: "reposteria",
    image: "/static/images/moldes-desmontables.jpg",
  },
  {
    id: 2,
    itemName: "Molde para gelatina",
    slug: "molde-para-gelatina",
    price: 250,
    category: "Repostería",
    slugCategory: "reposteria",
    image: "/static/images/molde-gelatina.jpg",
  },
  {
    id: 3,
    itemName: "Duyas",
    slug: "duyas",
    price: 100,
    category: "Repostería",
    slugCategory: "reposteria",
    image: "/static/images/duyas.png",
  },
  {
    id: 4,
    itemName: "Bolsas para repostería",
    slug: "bolsas-para-reposteria",
    price: 50,
    category: "Repostería",
    slugCategory: "reposteria",
    image: "/static/images/bolsas.jpg",
  },
  {
    id: 5,
    itemName: "Molde para pan",
    slug: "molde-para-pan",
    price: 120,
    category: "Repostería",
    slugCategory: "reposteria",
    image: "/static/images/molde-pan.jpg",
  },
  {
    id: 6,
    itemName: "Corta galletas",
    slug: "corta-galletas",
    price: 199,
    category: "Repostería",
    slugCategory: "reposteria",
    image: "/static/images/corta-galletas.png",
  },
];
